version: '3.7'

services:
  bot:
    container_name: bot
    build:
      context: .
    command: sh -c "alembic upgrade head && python3 bot.py"
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - postgres
    env_file: 
      - ./.env

  postgres:
    container_name: db
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.db.env
    

volumes:
  postgres-data:
