"""rename table from mentees to pairs

Revision ID: 1f6eb4f41dcb
Revises: 4e16cfd7f47c
Create Date: 2021-05-20 01:54:42.726571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f6eb4f41dcb'
down_revision = '4e16cfd7f47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('mentee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairs_id'), 'pairs', ['id'], unique=True)
    op.drop_index('ix_mentees_id', table_name='mentees')
    op.drop_table('mentees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.tg_id'], name='mentees_mentee_id_fkey'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.tg_id'], name='mentees_mentor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mentees_pkey')
    )
    op.create_index('ix_mentees_id', 'mentees', ['id'], unique=True)
    op.drop_index(op.f('ix_pairs_id'), table_name='pairs')
    op.drop_table('pairs')
    # ### end Alembic commands ###
