"""make is_mentee field to be nullable

Revision ID: 4e16cfd7f47c
Revises: e9eb24aee326
Create Date: 2021-05-20 00:37:32.912703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e16cfd7f47c'
down_revision = 'e9eb24aee326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
