"""use slug instead of url

Revision ID: e9eb24aee326
Revises: 0c620168a71b
Create Date: 2021-05-05 14:49:17.858591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9eb24aee326'
down_revision = '0c620168a71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('katas', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'katas', ['id'])
    op.drop_column('katas', 'url')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('katas', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'katas', type_='unique')
    op.drop_column('katas', 'slug')
    # ### end Alembic commands ###
